### ISSUE TITLE
Implementing multi-threaded sort

### ISSUE THREAD

**Issue by snarkmaster** [farsightsec/mtbl#7]
I was entertaining the idea of using multiple mtbl_sorter objects, one per thread, to get my key sorting done faster. The general plan was to manually coordinate a merge binary tree, with the number of active threads decreasing by a constant factor (2 or 3) every time. 

This seems like a good idea to try, since my machines have lots of cores. One catch is that an `mtbl_sorter` does not export a `mtbl_source` interface, which means that you cannot compose the output of `mtbl_sorter`s with `mtbl_merger` without dumping it to disk -- which would kind of defeat the point.

This is obviously outside what `mtbl` was designed for initially, but I thought you might be interested to know.

For now, I'm going with sorting and merging vectors using the standard library, and feeding the sorted values to `mtbl`.

**Comment by edmonds** [comment]
Yeah, multi-threaded sorting wasn't one of the original design goals for `mtbl`. It might be possible to glue something together with the `mtbl_iter`'s returned from `mtbl_sorter_iter()`, though it sounds like doing your own optimized sorting and passing the results directly into an `mtbl_writer` isn't that difficult either. It maybe preferable, even, since IIRC it's possible for C++'s `std::sort` to be faster than C's `qsort()` due to templating/inlining.

**Comment by snarkmaster** [comment]
Thanks for the reply, I think you're right and it's better not to add such feature-bloat to MTBL :)
